#!/usr/bin/env bash

set -e

if [[ -n "${DEBUG}" ]]; then
  set -x
fi

app_public_dir=$1

# Add symlink from persistent files volume to application's storage public dir.
if [[ -n "${app_public_dir}" ]]; then
  echo >&2
  echo >&2 "[INFO] Application's public storage directory specified, trying to symlink from files persistent volume"
  echo >&2

  if [[ -d "${app_public_dir}" ]]; then
    if [[ ! -L "${app_public_dir}" ]]; then
      if [[ "$(ls -A "${app_public_dir}")" ]]; then
        echo >&2
        echo >&2 "[ERROR] Failed to symlink public storage directory to a persistent volume"
        echo >&2 "        Directory ${app_public_dir} must not exists or be empty"
        echo >&2 "        (use files import to migrate existing public files)"
        echo >&2
        exit 1
      # If dir is not symlink and empty, remove it and link.
      else
        echo >&2
        echo >&2 "[INFO] Empty public storage dir detected: removing and symlinking '${app_public_dir}' -> ''${FILES_DIR}/public'"
        echo >&2
        rm -rf "${app_public_dir}"
        ln -sf "${FILES_DIR}/public" "${app_public_dir}"
      fi
    else
      echo "Symlink already in place"
    fi
  else
    echo >&2
    echo >&2 "[INFO] No public storage dir detected: just symlinking '${app_public_dir}' -> '${FILES_DIR}/public'"
    echo >&2
    ln -sf "${FILES_DIR}/public" "${app_public_dir}"
  fi
fi
