version: "3.7"
networks:
  default:
    internal: true
volumes:
  mariadb-data:
  mariadb-files:
services:
  # Always included even if PostgreSQL is included as Matomo only works with MySQL.
  # https://github.com/matomo-org/matomo/issues/500
  mariadb:
    image: ${REPOSITORY:-islandora}/mariadb:${TAG:-latest}
    volumes:
      - /opt/isle-db/mysql:/var/lib/mysql:delegated
      - /opt/isle-db/mysql-files:/var/lib/mysql-files:delegated
    # Allows for access to the database through traefik to support using Drush locally.
    # This should not be used in production.
    #
    # Since this is not http, but tcp traffic it does does not understand the concept of a "host".
    # so we must dedicate a port to it in traefik, and direct all traffic to this router: HostSNI(`*`).
    labels:
      - traefik.enable=true
      - traefik.tcp.services.${COMPOSE_PROJECT_NAME-isle-dc}-mysql.loadbalancer.server.port=3306
      - traefik.tcp.routers.${COMPOSE_PROJECT_NAME-isle-dc}-mysql_tcp.service=${COMPOSE_PROJECT_NAME-isle-dc}-mysql
      - traefik.tcp.routers.${COMPOSE_PROJECT_NAME-isle-dc}-mysql_tcp.entrypoints=mysql
      - traefik.tcp.routers.${COMPOSE_PROJECT_NAME-isle-dc}-mysql_tcp.rule=HostSNI(`*`)
    networks:
      default:
