version: "3.7"
networks:
  default:
    internal: true
  gateway:
    external:
      name: gateway
volumes:
  activemq-data:
services:
  activemq:
    image: ${REPOSITORY:-islandora}/activemq:${TAG:-latest}
    volumes:
      - activemq-data:/opt/activemq/data
    labels:
      # Do not expose in production.
      - traefik.enable=true
      - traefik.http.services.${COMPOSE_PROJECT_NAME-isle-dc}-activemq.loadbalancer.server.port=8161
      - traefik.http.routers.${COMPOSE_PROJECT_NAME-isle-dc}-activemq_http.service=${COMPOSE_PROJECT_NAME-isle-dc}-activemq
      - traefik.http.routers.${COMPOSE_PROJECT_NAME-isle-dc}-activemq_http.entrypoints=http
    networks:
      default:
      gateway: # Do not expose in production.