# This is just an example of which environment variables you can override for
# each of the services. If docker-compose.env.yml does not exist this file will
# be used to create it.
#
# These are, at a bare minimum, the settings you need to configure to deploy
# between environments. This is not an exhaustive list of all the environment
# variables available for each service. For the full list see the respective
# README.md file for the service in the isle-buildkit repository:
#
# - activemq: https://github.com/Islandora-Devops/isle-buildkit/tree/master/activemq/README.md
# - alpaca: https://github.com/Islandora-Devops/isle-buildkit/tree/master/alpaca/README.md
# - blazegraph: https://github.com/Islandora-Devops/isle-buildkit/tree/master/blazegraph/README.md
# - cantaloupe: https://github.com/Islandora-Devops/isle-buildkit/tree/master/cantaloupe/README.md
# - crayfits: https://github.com/Islandora-Devops/isle-buildkit/tree/master/crayfits/README.md
# - drupal: https://github.com/Islandora-Devops/isle-buildkit/tree/master/drupal/README.md
# - fcrepo: https://github.com/Islandora-Devops/isle-buildkit/tree/master/fcrepo/README.md
# - fits: https://github.com/Islandora-Devops/isle-buildkit/tree/master/fits/README.md
# - gemini: https://github.com/Islandora-Devops/isle-buildkit/tree/master/gemini/README.md
# - homarus: https://github.com/Islandora-Devops/isle-buildkit/tree/master/homarus/README.md
# - houdini: https://github.com/Islandora-Devops/isle-buildkit/tree/master/houdini/README.md
# - hypercube: https://github.com/Islandora-Devops/isle-buildkit/tree/master/hypercube/README.md
# - mariadb: https://github.com/Islandora-Devops/isle-buildkit/tree/master/mariadb/README.md
# - matomo: https://github.com/Islandora-Devops/isle-buildkit/tree/master/matomo/README.md
# - milliner: https://github.com/Islandora-Devops/isle-buildkit/tree/master/milliner/README.md
# - recast: https://github.com/Islandora-Devops/isle-buildkit/tree/master/recast/README.md
# - solr: https://github.com/Islandora-Devops/isle-buildkit/tree/master/solr/README.md
#
# Unfortunately there isn't a way to a way to use a variable value in multiple
# places, except through the `.env` file, which does not support multi-line
# variables, so for consistency sake all the values are duplicated here, rather
# than doing a mixed approach where some are defined in `env` files and some here.
version: "3.7"
services:
  activemq:
    environment:
      #
      # Password for default JAAS authentication: https://activemq.apache.org/security
      #
      ACTIVEMQ_PASSWORD: password
      #
      # Password to log into the ActiveMQ Web Console: https://activemq.apache.org/web-console
      #
      ACTIVEMQ_WEB_ADMIN_PASSWORD: password
  alpaca:
    environment:
      #
      # Must be exactly the same as ACTIVEMQ_PASSWORD.
      # 
      ALPACA_ACTIVEMQ_PASSWORD: password
      #
      # Password for admin user: https://karaf.apache.org/manual/latest/security 
      #
      ALPACA_KARAF_ADMIN_PASSWORD: password
  blazegraph:
    # No environment variables require overriding.
  cantaloupe:
    # No environment variables require overriding.
  crayfits:
    # No environment variables require overriding.
  database:
    environment:
      #
      # Password for the root user.
      # 
      MYSQL_ROOT_PASSWORD: password
  drupal:
    environment:
      #
      # Settings which the Drupal site exposes as links need to be corrected to use the edge name for those services.
      # If creating sub-sites you must specify each of these as the defaults would cause odd issues where it pulls
      # content from the main site rather than the sub site.
      #
      DRUPAL_DEFAULT_CANTALOUPE_URL: http://islandora.${COMPOSE_PROJECT_NAME-isle-dc}.localhost/cantaloupe/iiif/2
      DRUPAL_DEFAULT_FCREPO_HOST: fcrepo.${COMPOSE_PROJECT_NAME-isle-dc}.localhost
      DRUPAL_DEFAULT_MATOMO_URL: http://islandora.${COMPOSE_PROJECT_NAME-isle-dc}.localhost/matomo/
      DRUPAL_DEFAULT_SITE_URL: http://islandora.${COMPOSE_PROJECT_NAME-isle-dc}.localhost
      #
      # Salt for one-time login links, cancel links, form tokens, etc, if deploying multiple
      # instances of the site this must be set the same for all instances.
      #
      DRUPAL_DEFAULT_SALT: 9PPaL0CxZAIcq0l9wxgDGlCZrp7JdT_x7v9gVzpdbUjMt1PqDz3uD0Zy-i16DuJ1-Htuq5hqeg
      #
      # The administrator email account for the default site.
      # 
      DRUPAL_DEFAULT_ACCOUNT_EMAIL: admin@example.org
      #
      # The password of the admin account for the default site.
      # 
      DRUPAL_DEFAULT_ACCOUNT_PASSWORD: password
      #
      # The password Drupal uses to connect to the database for the default site. 
      #
      DRUPAL_DEFAULT_DB_PASSWORD: password
      #
      # Must match MYSQL_ROOT_PASSWORD, used to create the database / user.
      #
      DRUPAL_DEFAULT_DB_ROOT_PASSWORD: password
      #
      # JWT Key Pair 
      #
      DRUPAL_JWT_PRIVATE_KEY: |-
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpAIBAAKCAQEA6uK3nozywVaRCAB3FHdRZNHunSZvN/c31QimZAqQMGxj7JrG
        h1LF8JRX+XAQ+CJcPD9r6xXjKSS1Gqa2Os2wARr/9abIwG5QeNsrJ8GMt3Z/WICn
        NeaFAkUVviwKWcA61iFJWvTDAuI0hCaxArRKsk0BfFSMh+4u3JAdD9tUxUx6AAUX
        UCdtPyluaBd53wuB0r9xRlPnDw6I9QHfKK80Xrrsu1PYATgrsy69stzCln3KlO5O
        xc6O8OjMdjC2D2c3HmsO4CKPvvaVuaow/a9Pa3SNje4UXN+/1xUfQskxafP8CKVS
        r8xxtwzSureiskb5/98moAiutpUtp15yyAm0rwIDAQABAoIBAA0PZh5OwAC4C4Bi
        ZjyhFcmBUr8yL+Twvg3+WSIe5D2NCVFSmc9UbuUdmnaoIIlrf61p6Vo88VCMVfWR
        Z3iFj0/AbJMAHxF0EM1nglLHlEdvM018ec+pbaPeq4LTeA/dfGgDmcyQ53b1lO30
        KMt5st2PIpIDMX0tZTWmXbdP/rqplqiQmdwH0gv8PzEG6Y2ZVLBf5viH5IvVRpg7
        9nDqLfe2W2ylFib+CtleX626xTUzGcJ0aqTRP1UkY4Jj5PI2/yVqttYPkvJtxZco
        5/14AEMcu9FMBhADCSk/0y1TkKCGsi6/VNd78AB/RrZK32HfHCwTwxoXHQoaVKq6
        hNQfokECgYEA+keGdVJrXMDylamARQdDe/nNgljqZZhfkKKYCGeckNqjp3iqfmld
        /tqCPVxAO2mIo8dNNfM2MMv6loEPx9F2REe8k9NbWFrUZ486fMHPeO7WnHt92JyU
        DtfJJSZ1GdCki1PthmpmP8WdoF6VpLvr5AgwuYKAzkMNth+OV/dvgqkCgYEA8EEe
        E3mKvePHV/PVsLt6TaqJcZEKKu6L9EgeDyzv3zz4+2zG8MVctyUFyfSl4EIC/oJy
        X0T5Tj1l4A3mPwZOJfQOkXnr9TaPNff1zjNx12RhUZjFtJU5V+Wn1ldtzs+XwCFc
        x5O/B8LWYgV4bOixNlc6tTRq/m8Txvtde9vPa5cCgYEA3OOdnxRD31QHheFYbRPx
        Eo0xPNae4VWvGmb2SYywmQPuplMQHot+Qvy1L9SoeAc3alzvHytta3nLy2NS+yc5
        +x9ZJxrGJt/bUR8PHqarJu+ch/VR54ih/8uhImGjvknvv2wuWZC0d5pA+RYheofE
        tLgp0MCGUATMKC4HokmmqCkCgYBEjoBTlFIn33CJw3WNyeGbefdgZb/eAlYDbfTN
        5cfJDvAJZr/aAqdzR2hAecQ/mvaZw4V5dAgj8Fc6uRyjjVwNbngdwQm43km9X7VP
        ktSAXw96Jjr8TbygPVNIUYhvBEPMOnjsJlfTkiB0thToFvpChF+nR37kfbPKCv5h
        Epc8nwKBgQCdKyLi54Fm24nqEuZYbAxxGI9TVT7wJjoKGn64JWrXtX7xRltmJC3t
        nLwNCojcbyG4kVB+Myzr2OEtFkO45j83GjrZ4O+jCuSj+AmCxEcc7xNA9cgu9usG
        sQXdGmIIB0Cbk54OyHNdsZgZCXi9GTRF9uvYZKL9qktS+UZMJ1Xz/g==
        -----END RSA PRIVATE KEY-----
      #
      # All other *_JWT_PUBLIC keys should match this value exactly.
      # 
      DRUPAL_JWT_PUBLIC_KEY: |-
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6uK3nozywVaRCAB3FHdR
        ZNHunSZvN/c31QimZAqQMGxj7JrGh1LF8JRX+XAQ+CJcPD9r6xXjKSS1Gqa2Os2w
        ARr/9abIwG5QeNsrJ8GMt3Z/WICnNeaFAkUVviwKWcA61iFJWvTDAuI0hCaxArRK
        sk0BfFSMh+4u3JAdD9tUxUx6AAUXUCdtPyluaBd53wuB0r9xRlPnDw6I9QHfKK80
        Xrrsu1PYATgrsy69stzCln3KlO5Oxc6O8OjMdjC2D2c3HmsO4CKPvvaVuaow/a9P
        a3SNje4UXN+/1xUfQskxafP8CKVSr8xxtwzSureiskb5/98moAiutpUtp15yyAm0
        rwIDAQAB
        -----END PUBLIC KEY-----
  fcrepo:
    environment:
      #
      # The password Fedora uses to connect to the database.
      #
      FCREPO_DB_PASSWORD: password
      #
      # Must match MYSQL_ROOT_PASSWORD, used to create the database / user.
      #
      FCREPO_DB_ROOT_PASSWORD: password
      #
      # Definitive name of token for as defined in syn-settings.xml.
      #
      FCREPO_JWT_ADMIN_TOKEN: islandora
      #
      # Must be exactly the same as DRUPAL_JWT_PUBLIC_KEY.
      # 
      FCREPO_JWT_PUBLIC_KEY: |-
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6uK3nozywVaRCAB3FHdR
        ZNHunSZvN/c31QimZAqQMGxj7JrGh1LF8JRX+XAQ+CJcPD9r6xXjKSS1Gqa2Os2w
        ARr/9abIwG5QeNsrJ8GMt3Z/WICnNeaFAkUVviwKWcA61iFJWvTDAuI0hCaxArRK
        sk0BfFSMh+4u3JAdD9tUxUx6AAUXUCdtPyluaBd53wuB0r9xRlPnDw6I9QHfKK80
        Xrrsu1PYATgrsy69stzCln3KlO5Oxc6O8OjMdjC2D2c3HmsO4CKPvvaVuaow/a9P
        a3SNje4UXN+/1xUfQskxafP8CKVSr8xxtwzSureiskb5/98moAiutpUtp15yyAm0
        rwIDAQAB
        -----END PUBLIC KEY-----
  gemini:
    environment:
      #
      # The password Gemini uses to connect to the database.
      #
      GEMINI_DB_PASSWORD: password
      #
      # Must match MYSQL_ROOT_PASSWORD, used to create the database / user.
      #
      GEMINI_DB_ROOT_PASSWORD: password
      #
      # Must be exactly the same as FCREPO_JWT_ADMIN_TOKEN.
      #
      GEMINI_JWT_ADMIN_TOKEN: islandora 
      #
      # Must be exactly the same as DRUPAL_JWT_PUBLIC_KEY.
      # 
      GEMINI_JWT_PUBLIC_KEY: |-
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6uK3nozywVaRCAB3FHdR
        ZNHunSZvN/c31QimZAqQMGxj7JrGh1LF8JRX+XAQ+CJcPD9r6xXjKSS1Gqa2Os2w
        ARr/9abIwG5QeNsrJ8GMt3Z/WICnNeaFAkUVviwKWcA61iFJWvTDAuI0hCaxArRK
        sk0BfFSMh+4u3JAdD9tUxUx6AAUXUCdtPyluaBd53wuB0r9xRlPnDw6I9QHfKK80
        Xrrsu1PYATgrsy69stzCln3KlO5Oxc6O8OjMdjC2D2c3HmsO4CKPvvaVuaow/a9P
        a3SNje4UXN+/1xUfQskxafP8CKVSr8xxtwzSureiskb5/98moAiutpUtp15yyAm0
        rwIDAQAB
        -----END PUBLIC KEY-----
  homarus:
    environment:
      #
      # Must be exactly the same as FCREPO_JWT_ADMIN_TOKEN.
      #
      HOMARUS_JWT_ADMIN_TOKEN: islandora 
      #
      # Must be exactly the same as DRUPAL_JWT_PUBLIC_KEY.
      # 
      HOMARUS_JWT_PUBLIC_KEY: |-
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6uK3nozywVaRCAB3FHdR
        ZNHunSZvN/c31QimZAqQMGxj7JrGh1LF8JRX+XAQ+CJcPD9r6xXjKSS1Gqa2Os2w
        ARr/9abIwG5QeNsrJ8GMt3Z/WICnNeaFAkUVviwKWcA61iFJWvTDAuI0hCaxArRK
        sk0BfFSMh+4u3JAdD9tUxUx6AAUXUCdtPyluaBd53wuB0r9xRlPnDw6I9QHfKK80
        Xrrsu1PYATgrsy69stzCln3KlO5Oxc6O8OjMdjC2D2c3HmsO4CKPvvaVuaow/a9P
        a3SNje4UXN+/1xUfQskxafP8CKVSr8xxtwzSureiskb5/98moAiutpUtp15yyAm0
        rwIDAQAB
        -----END PUBLIC KEY-----
  houdini:
    environment:
      #
      # Must be exactly the same as FCREPO_JWT_ADMIN_TOKEN.
      #
      HOUDINI_JWT_ADMIN_TOKEN: islandora 
      #
      # Must be exactly the same as DRUPAL_JWT_PUBLIC_KEY.
      # 
      HOUDINI_JWT_PUBLIC_KEY: |-
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6uK3nozywVaRCAB3FHdR
        ZNHunSZvN/c31QimZAqQMGxj7JrGh1LF8JRX+XAQ+CJcPD9r6xXjKSS1Gqa2Os2w
        ARr/9abIwG5QeNsrJ8GMt3Z/WICnNeaFAkUVviwKWcA61iFJWvTDAuI0hCaxArRK
        sk0BfFSMh+4u3JAdD9tUxUx6AAUXUCdtPyluaBd53wuB0r9xRlPnDw6I9QHfKK80
        Xrrsu1PYATgrsy69stzCln3KlO5Oxc6O8OjMdjC2D2c3HmsO4CKPvvaVuaow/a9P
        a3SNje4UXN+/1xUfQskxafP8CKVSr8xxtwzSureiskb5/98moAiutpUtp15yyAm0
        rwIDAQAB
        -----END PUBLIC KEY-----
  hypercube:
    environment:
      #
      # Must be exactly the same as FCREPO_JWT_ADMIN_TOKEN.
      #
      HYPERCUBE_JWT_ADMIN_TOKEN: islandora 
      #
      # Must be exactly the same as DRUPAL_JWT_PUBLIC_KEY.
      # 
      HYPERCUBE_JWT_PUBLIC_KEY: |-
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6uK3nozywVaRCAB3FHdR
        ZNHunSZvN/c31QimZAqQMGxj7JrGh1LF8JRX+XAQ+CJcPD9r6xXjKSS1Gqa2Os2w
        ARr/9abIwG5QeNsrJ8GMt3Z/WICnNeaFAkUVviwKWcA61iFJWvTDAuI0hCaxArRK
        sk0BfFSMh+4u3JAdD9tUxUx6AAUXUCdtPyluaBd53wuB0r9xRlPnDw6I9QHfKK80
        Xrrsu1PYATgrsy69stzCln3KlO5Oxc6O8OjMdjC2D2c3HmsO4CKPvvaVuaow/a9P
        a3SNje4UXN+/1xUfQskxafP8CKVSr8xxtwzSureiskb5/98moAiutpUtp15yyAm0
        rwIDAQAB
        -----END PUBLIC KEY-----
  matomo:
    environment:
      #
      # The password Matomo uses to connect to the database.
      #
      MATOMO_DB_PASSWORD: password
      #
      # Must match MYSQL_ROOT_PASSWORD, used to create the database / user.
      #
      MATOMO_DB_ROOT_PASSWORD: password
      #
      # Administrator email.
      #
      MATOMO_USER_EMAIL: admin@example.org
      # To regenerate a the `MATOMO_USER_PASS` you must use the following
      # snippet of [PHP](https://matomo.org/faq/how-to/faq_191/).
      #
      # php -r 'echo password_hash(md5("password"), PASSWORD_DEFAULT) . "\n";'
      #
      # N.B. You must double up '$' characters to prevent them from being 
      # interpolated by docker-compose.yml
      MATOMO_USER_PASS: $$2y$$10$$S38e7HPM9LI3aOIvcnRsfuMCm4ipNP572QsvbCK60upoHVJ61hMrS
      #
      # Must be exactly the same as DRUPAL_DEFAULT_SITE_URL without the protocol.
      # 
      MATOMO_SITE_HOST: islandora.${COMPOSE_PROJECT_NAME-isle-dc}.localhost
      #
      # Timezone of site.
      #
      MATOMO_SITE_TIMEZONE: America/Halifax
  milliner:
    # No environment variables require overriding.
  recast:
    environment:
      #
      # Must be exactly the same as FCREPO_JWT_ADMIN_TOKEN.
      #
      RECAST_JWT_ADMIN_TOKEN: islandora 
      #
      # Must be exactly the same as DRUPAL_JWT_PUBLIC_KEY.
      # 
      RECAST_JWT_PUBLIC_KEY: |-
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6uK3nozywVaRCAB3FHdR
        ZNHunSZvN/c31QimZAqQMGxj7JrGh1LF8JRX+XAQ+CJcPD9r6xXjKSS1Gqa2Os2w
        ARr/9abIwG5QeNsrJ8GMt3Z/WICnNeaFAkUVviwKWcA61iFJWvTDAuI0hCaxArRK
        sk0BfFSMh+4u3JAdD9tUxUx6AAUXUCdtPyluaBd53wuB0r9xRlPnDw6I9QHfKK80
        Xrrsu1PYATgrsy69stzCln3KlO5Oxc6O8OjMdjC2D2c3HmsO4CKPvvaVuaow/a9P
        a3SNje4UXN+/1xUfQskxafP8CKVSr8xxtwzSureiskb5/98moAiutpUtp15yyAm0
        rwIDAQAB
        -----END PUBLIC KEY-----
  solr:
    # No environment variables require overriding.